// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vigia.Data;

#nullable disable

namespace Vigia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524164004_AdicionandoTabelasDeAgendamento")]
    partial class AdicionandoTabelasDeAgendamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Vigia.Entities.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AmbulanciaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AtendenteAprovadorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataHoraAprovacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataHoraFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataHoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraSolicitada")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnderecoDestino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnderecoOrigem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrioridadeConfirmada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrioridadeSugerida")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AmbulanciaId");

                    b.HasIndex("AtendenteAprovadorId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("Vigia.Entities.Ambulancia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("StatusDisponibilidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Ambulancias");
                });

            modelBuilder.Entity("Vigia.Entities.Atendente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Atendentes");
                });

            modelBuilder.Entity("Vigia.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContatoEmergenciaNome")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContatoEmergenciaTelefone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnderecoCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioridade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Vigia.Entities.DadosClinicos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alergias")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CardiopatiaGrave")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CartaoSus")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comorbidades")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CuidadosPaliativos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DoencaPulmonarCronicaDpoc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GestacaoAltoRisco")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Hemodialise")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicamentosUsoContinuo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PosOperatorioRecente")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("QuimioterapiaOuRadioterapia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TratamentoOncologico")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("DadosClinicos");
                });

            modelBuilder.Entity("Vigia.Entities.MobilidadeNecessidades", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CondicaoMobilidade")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NecessitaAcompanhante")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PacienteBeriatrico")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoSanguineo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TransporteExclusivoEmMaca")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsoContínuoDeOxigenio")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("MobilidadeNecessidades");
                });

            modelBuilder.Entity("Vigia.Entities.Agendamento", b =>
                {
                    b.HasOne("Vigia.Entities.Ambulancia", "Ambulancia")
                        .WithMany()
                        .HasForeignKey("AmbulanciaId");

                    b.HasOne("Vigia.Entities.Atendente", "AtendenteAprovador")
                        .WithMany()
                        .HasForeignKey("AtendenteAprovadorId");

                    b.HasOne("Vigia.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ambulancia");

                    b.Navigation("AtendenteAprovador");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Vigia.Entities.DadosClinicos", b =>
                {
                    b.HasOne("Vigia.Entities.Cliente", "Cliente")
                        .WithOne("DadosClinicos")
                        .HasForeignKey("Vigia.Entities.DadosClinicos", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Vigia.Entities.MobilidadeNecessidades", b =>
                {
                    b.HasOne("Vigia.Entities.Cliente", "Cliente")
                        .WithOne("Mobilidade")
                        .HasForeignKey("Vigia.Entities.MobilidadeNecessidades", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Vigia.Entities.Cliente", b =>
                {
                    b.Navigation("DadosClinicos");

                    b.Navigation("Mobilidade");
                });
#pragma warning restore 612, 618
        }
    }
}
