// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vigia.Data;

#nullable disable

namespace Vigia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Vigia.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContatoEmergenciaNome")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContatoEmergenciaTelefone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnderecoCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioridade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Vigia.Entities.DadosClinicos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alergias")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CardiopatiaGrave")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CartaoSus")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comorbidades")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CuidadosPaliativos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DoencaPulmonarCronicaDpoc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GestacaoAltoRisco")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Hemodialise")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicamentosUsoContinuo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PosOperatorioRecente")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("QuimioterapiaOuRadioterapia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TratamentoOncologico")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("DadosClinicos");
                });

            modelBuilder.Entity("Vigia.Entities.MobilidadeNecessidades", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CondicaoMobilidade")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NecessitaAcompanhante")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PacienteBeriatrico")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoSanguineo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TransporteExclusivoEmMaca")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsoContínuoDeOxigenio")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("MobilidadeNecessidades");
                });

            modelBuilder.Entity("Vigia.Entities.DadosClinicos", b =>
                {
                    b.HasOne("Vigia.Entities.Cliente", "Cliente")
                        .WithOne("DadosClinicos")
                        .HasForeignKey("Vigia.Entities.DadosClinicos", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Vigia.Entities.MobilidadeNecessidades", b =>
                {
                    b.HasOne("Vigia.Entities.Cliente", "Cliente")
                        .WithOne("Mobilidade")
                        .HasForeignKey("Vigia.Entities.MobilidadeNecessidades", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Vigia.Entities.Cliente", b =>
                {
                    b.Navigation("DadosClinicos");

                    b.Navigation("Mobilidade");
                });
#pragma warning restore 612, 618
        }
    }
}
